expr ::= comma_expr

comma_expr ::= equality_expr ("," comma_expr)? ;

equality_expr ::= comparison_expr  ( ( "!=" | "==" ) comparison_expr  )* ;

comparison_expr ::= term_expr  ( ( ">" | ">=" | "<" | "<=" ) term_expr  )* ;

term_expr ::= factor_expr ( ( "-" | "+" ) factor_expr  )* ;

factor_expr ::= unary_expr ( ( "/" | "*" ) unary_expr )* ;

unary_expr ::= ( "!" | "-" ) unary_expr | primary_expr ;

primary_expr ::= NUMBER | STRING | "true" | "false" | "nil" | "(" expr ")" ;
